version: "3.7"
services:
  psql:
    container_name: esus_psql
    restart: always
    image: postgres:13.5
    volumes:
      - ./data/psql_db:/var/lib/postgresql/data
      - ./data/backups:/home
    environment:
      - POSTGRES_DB="esus"
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="esus"
    ports:
      - "5432:5432"
  app:
    container_name: esus_app
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_DATABASE="esus"
        - POSTGRES_USERNAME="postgres"
        - POSTGRES_PASSWORD="esus"
        - TIMEZONE="America/Bahia"
    stdin_open: true
    tty: true
    volumes:
      - optEsus:/opt/e-SUS
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - psql
  cron:
    container_name: esus_cron
    restart: always
    build:
      context: cron
      dockerfile: Dockerfile
      args:
        - TIMEZONE="America/Bahia"
    volumes:
      - ./cron/crontab.txt:/crontab.txt
      - ./cron/app:/home
    environment:
      - POSTGRES_DB="esus"
      - POSTGRES_USER="postgres"
      - PGPASSWORD="esus"
    depends_on:
      - psql

volumes:
  optEsus: