database:
  app:
    container_name: esus_app
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_DATABASE="esus"
        - POSTGRES_USERNAME="postgres"
        - POSTGRES_PASSWORD="esus"
        - TIMEZONE="America/Bahia"
    stdin_open: true
    tty: true
    volumes:
      - optEsus:/opt/e-SUS
    ports:
      - "88:8080"
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: 'esus'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'esus'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: 'admin@pgadmin.org'
        PGADMIN_DEFAULT_PASSWORD: 'root'
      ports:
        - '8089:80'

volumes:
  postgres-data:
  optEsus: